version: '3.5'
services:

    db:
      container_name: 'postgres'
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
        # (HOST:CONTAINER)
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - pgdata:/var/lib/postgresql/data/
      networks:
        - proxy
      logging:
        driver: "json-file"
        options:
          max-file: "1"    # default 是 1
          max-size: "200m" # default 是 -1, 也就是沒有限制

    web:
      build: ./api
      entrypoint: /docker_api/docker-entrypoint.sh
      command: python manage.py runserver 0.0.0.0:8000
      restart: always

      # ref.
      # https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser
      environment:
        - DJANGO_SUPERUSER_USERNAME=admin
        - DJANGO_SUPERUSER_PASSWORD=admin1234
        - DJANGO_SUPERUSER_EMAIL=admin@twtrubiks.com

      volumes:
        - api_data:/docker_api
        # (HOST:CONTAINER)
      ports:
        - "8000:8000"
        # (HOST:CONTAINER)
      depends_on:
        - db
      networks:
        - proxy
      logging:
        driver: "json-file"
        options:
          max-file: "1"    # default 是 1
          max-size: "200m" # default 是 -1, 也就是沒有限制

volumes:
    api_data:
    pgdata:

networks:
  proxy:
    driver: bridge
    labels:
      com.docker.compose.network: my_network2