# Generated by Django 3.2.20 on 2023-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.TextField(default='img'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
