# Generated by Django 3.2.20 on 2023-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230829_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(),
        ),
    ]
