# Generated by Django 3.2.20 on 2023-08-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_test',
        ),
    ]
