# Generated by Django 3.2.20 on 2023-08-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_news_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='newss',
        ),
    ]
