# Generated by Django 3.2.20 on 2023-08-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
