# Generated by Django 3.2.20 on 2023-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=models.TextField(default='Default Article Text'),
        ),
    ]
